theme: jekyll-theme-minimal

#
# Site Settings
#

title: Updated Farm Directory

acknow: https://factcapstone.github.io/LandingPage/acknowledge.html

github:
  repository_url: https://github.com/FACTCapstone/FACTDirectory
  repository_nwo: FACTCapstone/FACTDirectory
  

content:
