theme: jekyll-theme-minimal

#
# Site Settings
#

title: Updated Farm Directory

github:
  repository_url: https://github.com/FACTCapstone/FACTDirectory
  repository_nwo: FACTCapstone/FACTDirectory

content:
